### PR TITLE
fix qos of trial_config subscriber to implement droppedpart challenge

### LINKED ISSUE #333: drop part challenge does not drop a part
I'm trying to test the drop part challenge, but the sim won't drop a part.  The other challenges I've tried work and I used the format shown in the configuration files part of the docs (... drop_after: 0 delay: 0.5) cut and pasted directly, with correct indenting. I can include things in the same trial such as faulty_part and those work without a problem.

Is it working for everyone else?

### PR DESCRIPTION
**Pull request by saahu27**
The Dropped part Challenge does not work because of the Qos profile mismatch between the publisher and subscriber.

### CODE REVIEW

File: ariac_plugins/src/vacuum_gripper_plugin.cpp [hunk 1]
```diff
@@ -155,8 +155,11 @@ namespace ariac_plugins
     impl_->first_publish_ = true;
 
     // Connect Subscribers
+    rclcpp::QoS custom_qos(1);
```
Comment (jaybrecht) [inline ariac_plugins/src/vacuum_gripper_plugin.cpp]: To keep consistency with the task manager plugin use this format for the QoS:

```cpp
rclcpp::QoS qos_profile = rclcpp::QoS(rclcpp::KeepLast(1)).transient_local().reliable();

impl_->trial_config_sub_ = impl_->ros_node_->create_subscription<ariac_msgs::msg::Trial>(
        "/ariac/trial_config", qos.get_subscription_qos("/ariac/trial_config", qos_profile),
        std::bind(&VacuumGripperPluginPrivate::OnTrialCallback, impl_.get(), std::placeholders::_1));
```

**Review by jaybrecht — CHANGES_REQUESTED** [review]
Thanks for figuring out that it was a QoS issue with the subscription. Can you update with the change I requested.

**Review by jaybrecht — APPROVED** [review]
